[package]
name = "tetris"
version = "0.1.0"
authors = ["etoledom <etoledom@icloud.com>"]
edition = "2018"

[lib]
name = "tetris"
crate-type = ["staticlib"]

[dependencies]
tetris_core = "0.2.1"
rand = "0.6.5"
